services:


  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATA_SOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATA_SOURCE_PASSWORD}
      POSTGRES_DB: ${DATA_SOURCE_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/

volumes:
  pgdata: